/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TCodigoRouteImport } from './routes/t.$codigo'
import { Route as TCodigoAdminRouteImport } from './routes/t.$codigo.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodigoRoute = TCodigoRouteImport.update({
  id: '/t/$codigo',
  path: '/t/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodigoAdminRoute = TCodigoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TCodigoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$codigo': typeof TCodigoRouteWithChildren
  '/t/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$codigo': typeof TCodigoRouteWithChildren
  '/t/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$codigo': typeof TCodigoRouteWithChildren
  '/t/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t/$codigo' | '/t/$codigo/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t/$codigo' | '/t/$codigo/admin'
  id: '__root__' | '/' | '/t/$codigo' | '/t/$codigo/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TCodigoRoute: typeof TCodigoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$codigo': {
      id: '/t/$codigo'
      path: '/t/$codigo'
      fullPath: '/t/$codigo'
      preLoaderRoute: typeof TCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$codigo/admin': {
      id: '/t/$codigo/admin'
      path: '/admin'
      fullPath: '/t/$codigo/admin'
      preLoaderRoute: typeof TCodigoAdminRouteImport
      parentRoute: typeof TCodigoRoute
    }
  }
}

interface TCodigoRouteChildren {
  TCodigoAdminRoute: typeof TCodigoAdminRoute
}

const TCodigoRouteChildren: TCodigoRouteChildren = {
  TCodigoAdminRoute: TCodigoAdminRoute,
}

const TCodigoRouteWithChildren =
  TCodigoRoute._addFileChildren(TCodigoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TCodigoRoute: TCodigoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
