/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TCodigoRouteImport } from './routes/t.$codigo'
import { Route as TCodigoAdminRouteImport } from './routes/t_.$codigo.admin'

const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodigoRoute = TCodigoRouteImport.update({
  id: '/t/$codigo',
  path: '/t/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodigoAdminRoute = TCodigoAdminRouteImport.update({
  id: '/t_/$codigo/admin',
  path: '/t/$codigo/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/t/$codigo': typeof TCodigoRoute
  '/t/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/t/$codigo': typeof TCodigoRoute
  '/t/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/t/$codigo': typeof TCodigoRoute
  '/t_/$codigo/admin': typeof TCodigoAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar' | '/t/$codigo' | '/t/$codigo/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar' | '/t/$codigo' | '/t/$codigo/admin'
  id: '__root__' | '/' | '/criar' | '/t/$codigo' | '/t_/$codigo/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  TCodigoRoute: typeof TCodigoRoute
  TCodigoAdminRoute: typeof TCodigoAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$codigo': {
      id: '/t/$codigo'
      path: '/t/$codigo'
      fullPath: '/t/$codigo'
      preLoaderRoute: typeof TCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t_/$codigo/admin': {
      id: '/t_/$codigo/admin'
      path: '/t/$codigo/admin'
      fullPath: '/t/$codigo/admin'
      preLoaderRoute: typeof TCodigoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  TCodigoRoute: TCodigoRoute,
  TCodigoAdminRoute: TCodigoAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
